### ISSUE TITLE
Troubles with local start

### ISSUE THREAD

**Issue by Pashaster12** [A-Lawrence/laravel-ipboard#2]
Hello! I have the site using IPB with this package in production. Site works with https. When I try to start it locally, I got the error "cURL error 60: SSL certificate problem: unable to get local issuer certificate" when I call the Ipboard::getMemberById();

Help me, please, what's the probable reason of this error and how can I solve it?

**Comment by A-Lawrence** [comment]
That's an error with your local curl setup.  

https://superuser.com/questions/442793/why-cant-curl-properly-verify-a-certificate-on-windows
